spring:
  application:
    name: user-service
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 2
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USER:root}
    password: ${DB_PASS:}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URI:http://localhost}:8761/eureka
  instance:
    preferIpAddress: true